kinematics:
  1_s:
    x: 0
    y: 0
    z: 0.650
    roll: 0
    pitch: 0
    yaw: 0
  2_l:
    x: 0.325
    y: 0
    z: 0
    roll: 0
    pitch: !degrees -90
    yaw: !degrees -90
  3_u:
    x: 1.150
    y: 0
    z: 0
    roll: !degrees 180
    pitch: 0
    yaw: 0
  4_r:
    x: 0.300
    y: 0
    z: 0
    roll: !degrees -90
    pitch: 0
    yaw: 0
  5_b:
    x: 0
    y: 0
    z: -1.225
    roll: !degrees 90
    pitch: 0
    yaw: 0
  6_t:
    x: 0
    y: -0.225
    z: 0
    roll: !degrees -90
    pitch: 0
    yaw: 0
