# Visualisation

mesh_files:
  base:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/collision/base_link.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/visual/link_1_s.stl"
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0

  1_s:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/visual/link_1_s.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/collision/link_1_s.stl"
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0

  2_l:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/visual/link_2_l.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/collision/link_2_l.stl"
    x: 0
    y: 0
    z: 0
    roll: !degrees 90
    pitch: 0
    yaw: !degrees 90

  3_u:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180/visual/link_3_u.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180/collision/link_3_u.stl"
    x: 0
    y: 0
    z: 0
    roll: !degrees -90
    pitch: 0
    yaw: !degrees -90

  4_r:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180/visual/link_4_r.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180/collision/link_4_r.stl"
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: !degrees 90
    yaw: 0

  5_b:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/visual/link_5_b.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/collision/link_5_b.stl"
    x: 0
    y: 0
    z: 0
    roll: !degrees -90
    pitch: 0
    yaw: !degrees -90

  6_t:
    visual:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/visual/link_6_t.stl"
      material: # Not used. This URDF uses <xacro:material_yaskawa_blue/>. Still required to have values.
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://motoman_gp180_support/meshes/gp180_120/collision/link_6_t.stl"
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: !degrees 90
    yaw: 0
