kinematic_offsets:
  1_s:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  2_l:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  3_u:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  4_r:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  5_b:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  6_t:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
